# Generated by Django 2.1.5 on 2019-03-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0069_auto_20190225_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='language_code',
            field=models.CharField(default='en-us', max_length=35),
        ),
    ]
