# Generated by Django 2.1.5 on 2019-03-07 18:10

from django.db import migrations, models
import saleor.account.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20181011_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='addresses',
        ),
        migrations.RemoveField(
            model_name='user',
            name='default_billing_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='default_shipping_address',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='billing_address',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, default='1970-1-1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('man', 'Man'), ('woman', 'Woman')], default='man', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=saleor.account.models.PossiblePhoneNumberField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('industry', 'Industry')], default='individual', max_length=20),
        ),
    ]
